name: event_bus_plus
description: Event Bus for Dart.
version: 0.6.2
homepage: https://github.com/AndrewPiterov/event_bus_plus

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies: 
  clock: ^1.1.0
  equatable: ^2.0.5
  logger: ^2.0.2+1
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^3.0.0
  given_when_then_unit_test: ^0.2.1
  shouldly: ^0.5.0+1
  test: ^1.22.0

