name: event_bus_plus
description: Event Bus for Dart.
version: 0.2.0
homepage: https://github.com/AndrewPiterov/event_bus_plus

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies: 
  clock: ^1.1.1
  equatable: ^2.0.3
  rxdart: ^0.27.5

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1
  given_when_then_unit_test: ^0.1.0
  shouldly: ^0.5.0+1

