name: event_bus_plus
description: Event Bus for Dart.
version: 0.0.2+1
homepage: https://github.com/AndrewPiterov/event_bus_plus

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies: 
  equatable: ^2.0.3
  rxdart: ^0.27.3


dev_dependencies:
  test: ^1.20.1
  flutter_lints: ^1.0.4
  given_when_then_unit_test: ^0.0.10
  shouldly: ^0.5.0

